DROP DATABASE IF EXISTS myfiles;

CREATE DATABASE IF NOT EXISTS myfiles;

USE myfiles;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES, CREATE TEMPORARY TABLES
ON myfiles.* TO 'root'@'localhost' IDENTIFIED BY 'password';

CREATE TABLE IF NOT EXISTS files (
    id mediumint UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    mimetype VARCHAR(64) NOT NULL,
    uniqid VARCHAR(16) NOT NULL,
    size int UNSIGNED NOT NULL,
    created_at DATETIME DEFAULT '2019-01-01 00:00:00',
    PRIMARY KEY (id)
) ENGINE=InnoDB;
